apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-authz-policy
  namespace: open-cluster-management-observability
data:
  policy.rego: |
    package authz

    import data.kubernetes.observabilityaccesspolicies
    import rego.v1

    _log_signal := "logs"

    _read_permission := "read"

    _application_scope := "application"
    _infrastructure_scope := "infrastructure"

    _rule_tenants_key := "tenants"
    _rule_signals_key := "signals"
    _rule_namespaces_key := "namespaces"
    _rule_scope_key := "resourceScope"
    _rule_permission_key := "permission"

    _request_selectors_key := "selectors"
    _request_metadata_key := "metadataOnly"
    _request_wildcard_selectors_key := "wildcardSelectors"
    _request_namespace_label_key := "k8s_namespace_name"
    _request_log_type_label_key := "log_type"

    _unauthorized_wildcard_selectors := "Access Denied: Your user query contains wildcard selectors which are currently unsupported."
    _missing_policies_deny_message := "Access Denied: Your user '%s' or groups '%s' are not configured in any ObservabilityAccessPolicies in the hub cluster."
    _unauthorized_tenant_message := "Access Denied: You do not have permission for the tenant '%s'."
    _missing_type_label := "Access Denied: To query logs you need to provide the label \"log_type\" with either \"application\", \"infrastructure\" or \"audit\"."
    _missing_signal_permissions_for_tenant := "Access Denied: You do not have permission '%s' to access the signal '%s' for the tenant '%s'."
    _missing_query_permissions_for_tenant := "Access Denied: You do not have permission to query the signal '%s' using the scope '%s' for the tenant '%s'."
    _forbidden_namespaces_in_scope := "Access Denied: Your log query for the tenant '%s' contains the following namespaces that are not allowed for the scope '%s': %s."
    _forbidden_namespaces := "Access Denied: Your '%s' query for the tenant '%s' using the scope '%s' contains the following namespaces that are not allowed to be queried: %s."
    _missing_namespaces := "Access Denied: Your '%s' query for the tenant '%s' using the scope '%s' does not specify any namespaces to query."


    # The new main rule to be queried by the API.
    # It composes the final response object.
    decision := {
        "allowed": allow,
        "deny_reasons": deny,
    }

    # A request is allowed if there are no deny messages.
    default allow = false
    allow if {
        count(deny) == 0
    }

    # The 'deny' rule will return a message on why the user was denied access.
    deny[msg] if {
        msg := _validate_no_wildcard_selectors(input)
    }

    _validate_no_wildcard_selectors(request_input) := _unauthorized_wildcard_selectors if {
        # Rule 1: Deny if the request contains wildcard selectors
        object.get(request_input.extras, _request_wildcard_selectors_key, false) == true
    }

    _validate_no_wildcard_selectors(request_input) := msg if {
        # Next Rule Path
        object.get(request_input.extras, _request_wildcard_selectors_key, false) != true

        # Collect all policies that are relevant to this user.
        applicable_policies := {policy |
            policy := observabilityaccesspolicies[_][_]
            _subject_matches(policy.spec.subjects, request_input.subject, request_input.groups)
        }

        msg := _validate_policies_exist(request_input, applicable_policies)
    }

    _validate_policies_exist(request_input, applicable_policies) := msg if {
        # Rule 2: Deny if the user doesn't match ANY policy at all.

        count(applicable_policies) == 0
        msg := sprintf(_missing_policies_deny_message, [request_input.subject, request_input.groups])
    }

    _validate_policies_exist(request_input, applicable_policies) := msg if {
        # Next Rule Path

        # Collect all policies that match the tenant.
        count(applicable_policies) > 0
        tenant_rules := {rule |
            some policy in applicable_policies
            some rule in policy.spec.accessRules
            _element_match_or_wildcard(object.get(rule, _rule_tenants_key, []), request_input.tenant)
        }

        msg := _validate_tenants_referenced(request_input, tenant_rules)
    }

    _validate_tenants_referenced(request_input, tenant_rules) := msg if {
        # Rule 3: Deny if the user has policies, but none grant access to the requested tenant.

        count(tenant_rules) == 0
        msg := sprintf(_unauthorized_tenant_message, [request_input.tenant])
    }

    _validate_tenants_referenced(request_input, tenant_rules) := msg if {
        # Next Rule Path
        # Check if any of those rules grant permission for the signal.
        count(tenant_rules) > 0
        applicable_rules := [rule |
            some rule in tenant_rules
            _element_match(object.get(rule, _rule_permission_key, []), request_input.permission)
            _element_match(object.get(rule, _rule_signals_key, []), request_input.resource)
        ]

        msg := _validate_signal_permissions_for_tenant(request_input, applicable_rules)
    }

    _validate_signal_permissions_for_tenant(request_input, applicable_rules) := msg if {
        # Rule 4: Deny if the user has policies for the tenant, but not for the requested signal and permission.

        count(applicable_rules) == 0
        msg := sprintf(_missing_signal_permissions_for_tenant, [request_input.permission,
        request_input.resource, request_input.tenant])
    }

    _validate_signal_permissions_for_tenant(request_input, applicable_rules) := msg if {
        # Next Rule Path

        count(applicable_rules) > 0
        msg := _signal_request_validation(request_input, applicable_rules)
    }

    _signal_request_validation(request_input, applicable_rules) := msg if {
        # Skip rule for other signals
        request_input.resource != _log_signal
        request_input.permission == _read_permission

        msg := _pre_validate_scope_permissions(request_input, applicable_rules)
    }

    _signal_request_validation(request_input, applicable_rules) := _missing_type_label if {
        # Rule 5: Deny logs read requests that are missing the scope label.
        request_input.resource == _log_signal
        request_input.permission == _read_permission
        not _is_metadata_request(request_input)

        _extract_scope(request_input) == ""
    }

    _signal_request_validation(request_input, applicable_rules) := _missing_type_label if {
        # Rule 5: Deny logs read requests for metadata that specify namespaces
        request_input.resource == _log_signal
        request_input.permission == _read_permission
        _is_metadata_request(request_input)
        extract_namespaces := _extract_namespaces(request_input)
        count(extract_namespaces) > 0

        _extract_scope(request_input) == ""
    }

    _signal_request_validation(request_input, applicable_rules) := msg if {
        # Next Rule Path for Logs
        request_input.resource == _log_signal
        request_input.permission == _read_permission

        _extract_scope(request_input) != ""
        msg := _pre_validate_scope_permissions(request_input, applicable_rules)
    }

    _pre_validate_scope_permissions(request_input, applicable_rules) := msg if {
        # Pre validation for scope permissions
        request_scope := _extract_scope_with_default(request_input)

        filtered_applicable_rules := [rule |
            some rule in applicable_rules
            object.get(rule, _rule_scope_key, _application_scope) == request_scope
        ]
        msg := _validate_scope_permissions(request_input, filtered_applicable_rules, request_scope)
    }

    _validate_scope_permissions(request_input, applicable_rules, request_scope) := msg if {
        # Rule 6: Deny if the user has policies for the tenant and signal, but not for the requested scope.
        count(applicable_rules) == 0
        msg := sprintf(_missing_query_permissions_for_tenant, [request_input.resource, request_scope,
        request_input.tenant])
    }

    _validate_scope_permissions(request_input, applicable_rules, request_scope) := msg if {
        # Next Rule Path for other signals

        request_input.resource != _log_signal
        count(applicable_rules) > 0
        _is_application_scope(_extract_scope(request_input))

        msg := _validate_application_query(request_input, applicable_rules, request_scope)
    }

    _validate_scope_permissions(request_input, applicable_rules, request_scope) := msg if {
        # Next Rule Path for Logs

        request_input.resource == _log_signal
        count(applicable_rules) > 0

        invalid_namespaces := _extract_namespaces_outside_of_scope(applicable_rules, request_scope)
        msg := _validate_scope_namespace_conflicts(request_input, applicable_rules, request_scope, invalid_namespaces)
    }

    _validate_application_query(request_input, applicable_rules, request_scope) := msg if {
        # Rule 7: Deny if the user has policies for the tenant and signal, but not for the requested namespaces.
        unauthorized_namespaces := _extract_unauthorized_namespaces(input, applicable_rules, request_scope)
        count(unauthorized_namespaces) > 0
        msg := sprintf(_forbidden_namespaces, [request_input.resource, request_input.tenant, request_scope,
        unauthorized_namespaces])
    }

    _validate_application_query(request_input, applicable_rules, request_scope) := msg if {
        not _is_metadata_request(request_input)

        requested_namespaces := _extract_namespaces(request_input)
        count(requested_namespaces) == 0
        msg := sprintf(_missing_namespaces, [request_input.resource, request_input.tenant, request_scope])
    }

    _validate_scope_namespace_conflicts(request_input, applicable_rules, request_scope, invalid_namespaces) := msg if {
        # Rule 8: Deny if the user has policies for the tenant and signal, but the requested namespaces do not match the scope.
        count(invalid_namespaces) > 0
        msg := sprintf(_forbidden_namespaces_in_scope, [request_input.tenant, request_scope, invalid_namespaces])
    }

    _validate_scope_namespace_conflicts(request_input, applicable_rules, request_scope, invalid_namespaces) := msg if {
        # Next Rule Path for Logs Scope Application
        count(invalid_namespaces) == 0
        _is_application_scope(_extract_scope(request_input))
        msg := _validate_application_query(request_input, applicable_rules, request_scope)
    }

    # _element_match: True if the requested element is in the set of elements or
    # is a wildcard.
    _element_match(elements, requested_element) if {
        some element in elements
        element == requested_element
    }

    # _element_match_or_wildcard: True if the requested element is in the set of elements or
    # is a wildcard.
    _element_match_or_wildcard(elements, requested_element) if {
        some element in elements
        element == "*" # Wildcard element allows access to any requested element
    }

    _element_match_or_wildcard(elements, requested_element) if {
        _element_match(elements, requested_element)
    }

    # _is_application_scope: True if the request is for the application scope or
    # doesn't specify a scope.
    _is_application_scope(request_scope) if {
        request_scope in {_application_scope, ""}
    }

    # _extract_unauthorized_namespaces: True if the request is a query request without specifying a namespace or
    # references namespace to which the user does not have access
    _extract_unauthorized_namespaces(request_input, applicable_rules, scope) := unauthorized_namespaces if {
        requested_namespaces := _extract_namespaces(request_input)
        count(requested_namespaces) > 0

        unauthorized_namespaces := {namespace |
            some namespace in requested_namespaces
            every rule in applicable_rules {
                not _element_match_or_wildcard(object.get(rule, _rule_namespaces_key, []), namespace)
            }
        }
    }

    # _is_metadata_request: True if the request is a metadata request.
    _is_metadata_request(request_input) if {
        object.get(request_input.extras, _request_metadata_key, false) == true
    }

    # _extract_namespaces: Extracts the list of namespaces from the request input.
    _extract_namespaces(request_input) := namespace_list if {
        selectors := object.get(request_input.extras, _request_selectors_key, {})
        namespace_list := object.get(selectors, _request_namespace_label_key, [])
    }

    # _extract_scope: Extracts the value of the scope label from the request input.
    _extract_scope(request_input) := scope if {
        selectors := object.get(request_input.extras, _request_selectors_key, {})
        scopes := object.get(selectors, _request_log_type_label_key, [])
        count(scopes) != 1
        scope := ""
    }

    _extract_scope(request_input) := scope if {
        selectors := object.get(request_input.extras, _request_selectors_key, {})
        scopes := object.get(selectors, _request_log_type_label_key, [])
        count(scopes) == 1
        scope := scopes[0]
    }

    _extract_scope_with_default(request_input) := scope if {
        selectors := object.get(request_input.extras, _request_selectors_key, {})
        scopes := object.get(selectors, _request_log_type_label_key, [])
        count(scopes) != 1
        scope :=  "application"
    }
    _extract_scope_with_default(request_input) := scope if {
        selectors := object.get(request_input.extras, _request_selectors_key, {})
        scopes := object.get(selectors, _request_log_type_label_key, [])
        count(scopes) == 1
        scope := scopes[0]
    }

    # ---- Tenant Helper Rules ----

    # _subject_matches: True if the user or any of their groups match a subject in the policy.
    _subject_matches(policy_subjects, user_subject, user_groups) if {
        some subject in policy_subjects
        subject.kind == "User"
        subject.name == user_subject
    }

    _subject_matches(policy_subjects, user_subject, user_groups) if {
        some subject in policy_subjects
        some group in user_groups
        subject.kind == "Group"
        subject.name == group
    }

    # ---- Log Specific Helper Rules ----

    # _extract_namespaces_outside_of_scope: True if the requested namespaces do not match the scope of the policy.
    # mainly used by Log queries.
    _extract_namespaces_outside_of_scope(applicable_rules, request_scope) := invalid_namespaces if {
        request_scope == _infrastructure_scope
        requested_namespaces := _extract_namespaces(input)
        invalid_namespaces := {ns | some ns in requested_namespaces; not _is_infrastructure_namespace(ns)}
    }

    _extract_namespaces_outside_of_scope(applicable_rules, request_scope) := invalid_namespaces if {
        request_scope == _application_scope
        requested_namespaces := _extract_namespaces(input)
        invalid_namespaces := {ns | some ns in requested_namespaces; _is_infrastructure_namespace(ns)}
    }

    # _is_infrastructure_namespace: True if requested namespace is an infrastructure namespace.
    _is_infrastructure_namespace("default") := "default"

    _is_infrastructure_namespace(requested_namespace) if {
        startswith(requested_namespace, "openshift-")
    }

    _is_infrastructure_namespace(requested_namespace) if {
        startswith(requested_namespace, "kube-")
    }
