apiVersion: v1
kind: Service
metadata:
  name: mcoa-opa
  namespace: open-cluster-management-observability
spec:
  ports:
  - name: http
    port: 8181
    targetPort: 8181
  selector:
    app: mcoa-opa
